DROP TABLE IF EXISTS countries;
CREATE TABLE IF NOT EXISTS countries (
    id INT AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR(100) NOT NULL,
    code VARCHAR(20) NOT NULL UNIQUE,
    active BOOLEAN NOT NULL DEFAULT true,
    description TEXT,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
)  ENGINE=INNODB;

INSERT INTO countries(name, code) VALUES('Chile', 'CL');
INSERT INTO countries(name, code) VALUES('India', 'IND');
INSERT INTO countries(name, code) VALUES('Unites States', 'USA');


DROP TABLE IF EXISTS regions;
CREATE TABLE regions (
  id int(11) NOT NULL AUTO_INCREMENT PRIMARY KEY,
  name varchar(64) NOT NULL,
  ordinal varchar(4) NOT NULL UNIQUE,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  country_id int(11) NOT NULL,
  FOREIGN KEY (country_id) REFERENCES countries(id)
) ENGINE=INNODB;

INSERT INTO regions (country_id,name,ordinal)
VALUES
    (1,'Arica y Parinacota','XV'),
    (1,'Tarapacá','I'),
    (1,'Antofagasta','II'),
    (1,'Atacama','III'),
    (1,'Coquimbo','IV'),
    (1,'Valparaiso','V'),
    (1,'Metropolitana de Santiago','RM'),
    (1,'Libertador General Bernardo O\'Higgins','VI'),
    (1,'Maule','VII'),
    (1,'Biobío','VIII'),
    (1,'La Araucanía','IX'),
    (1,'Los Ríos','XIV'),
    (1,'Los Lagos','X'),
    (1,'Aisén del General Carlos Ibáñez del Campo','XI'),
    (1,'Magallanes y de la Antártica Chilena','XII');

DROP TABLE IF EXISTS provincias;
CREATE TABLE provincias (
  id int(11) NOT NULL AUTO_INCREMENT PRIMARY KEY,
  name varchar(64) NOT NULL,
  region_id int(11) NOT NULL,
  FOREIGN KEY (region_id) REFERENCES regions(id)
) ENGINE=INNODB;

INSERT INTO provincias (name,region_id)
VALUES
	('Arica',1),
    ('Parinacota',1),
    ('Iquique',2),
    ('El Tamarugal',2),
    ('Antofagasta',3),
    ('El Loa',3),
    ('Tocopilla',3),
    ('Chañaral',4),
    ('Copiapó',4),
    ('Huasco',4),
    ('Choapa',5),
    ('Elqui',5),
    ('Limarí',5),
    ('Isla de Pascua',6),
    ('Los Andes',6),
    ('Petorca',6),
    ('Quillota',6),
    ('San Antonio',6),
    ('San Felipe de Aconcagua',6),
    ('Valparaiso',6),
    ('Chacabuco',7),
    ('Cordillera',7),
    ('Maipo',7),
    ('Melipilla',7),
    ('Santiago',7),
    ('Talagante',7),
    ('Cachapoal',7),
    ('Cardenal Caro',8),
    ('Colchagua',8),
    ('Cauquenes',9),
    ('Curicó',9),
    ('Linares',9),
    ('Talca',9),
    ('Arauco',10),
    ('Bio Bío',10),
    ('Concepción',10),
    ('Ñuble',10),
    ('Cautín',11),
    ('Malleco',11),
    ('Valdivia',12),
    ('Ranco',12),
    ('Chiloé',13),
    ('Llanquihue',13),
    ('Osorno',13),
    ('Palena',13),
    ('Aisén',14),
    ('Capitán Prat',14),
    ('Coihaique',14),
    ('General Carrera',14),
    ('Antártica Chilena',15),
    ('Magallanes',15),
    ('Tierra del Fuego',15),
    ('Última Esperanza',15);

DROP TABLE IF EXISTS comunas;
CREATE TABLE comunas (
  id int(11) NOT NULL AUTO_INCREMENT PRIMARY KEY,
  name varchar(64) NOT NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  provincia_id int(11) NOT NULL,
  FOREIGN KEY (provincia_id) REFERENCES provincias(id)
) ENGINE=INNODB;

INSERT INTO comunas (name,provincia_id)
VALUES
	('Arica',1),
	('Camarones',1),
	('General Lagos',2),
	('Putre',2),
	('Alto Hospicio',3),
	('Iquique',3),
	('Camiña',4),
	('Colchane',4),
	('Huara',4),
	('Pica',4),
	('Pozo Almonte',4),
	('Antofagasta',5),
	('Mejillones',5),
	('Sierra Gorda',5),
	('Taltal',5),
	('Calama',6),
	('Ollague',6),
	('San Pedro de Atacama',6),
	('María Elena',7),
	('Tocopilla',7),
	('Chañaral',8),
	('Diego de Almagro',8),
	('Caldera',9),
	('Copiapó',9),
	('Tierra Amarilla',9),
	('Alto del Carmen',10),
	('Freirina',10),
	('Huasco',10),
	('Vallenar',10),
	('Canela',11),
	('Illapel',11),
	('Los Vilos',11),
	('Salamanca',11),
	('Andacollo',12),
	('Coquimbo',12),
	('La Higuera',12),
	('La Serena',12),
	('Paihuaco',12),
	('Vicuña',12),
	('Combarbalá',13),
	('Monte Patria',13),
	('Ovalle',13),
	('Punitaqui',13),
	('Río Hurtado',13),
	('Isla de Pascua',14),
	('Calle Larga',15),
	('Los Andes',15),
	('Rinconada',15),
	('San Esteban',15),
	('La Ligua',16),
	('Papudo',16),
	('Petorca',16),
	('Zapallar',16),
	('Hijuelas',17),
	('La Calera',17),
	('La Cruz',17),
	('Limache',17),
	('Nogales',17),
	('Olmué',17),
	('Quillota',17),
	('Algarrobo',18),
	('Cartagena',18),
	('El Quisco',18),
	('El Tabo',18),
	('San Antonio',18),
	('Santo Domingo',18),
	('Catemu',19),
	('Llaillay',19),
	('Panquehue',19),
	('Putaendo',19),
	('San Felipe',19),
	('Santa María',19),
	('Casablanca',20),
	('Concón',20),
	('Juan Fernández',20),
	('Puchuncaví',20),
	('Quilpué',20),
	('Quintero',20),
	('Valparaíso',20),
	('Villa Alemana',20),
	('Viña del Mar',20),
	('Colina',21),
	('Lampa',21),
	('Tiltil',21),
	('Pirque',22),
	('Puente Alto',22),
	('San José de Maipo',22),
	('Buin',23),
	('Calera de Tango',23),
	('Paine',23),
	('San Bernardo',23),
	('Alhué',24),
	('Curacaví',24),
	('María Pinto',24),
	('Melipilla',24),
	('San Pedro',24),
	('Cerrillos',25),
	('Cerro Navia',25),
	('Conchalí',25),
	('El Bosque',25),
	('Estación Central',25),
	('Huechuraba',25),
	('Independencia',25),
	('La Cisterna',25),
	('La Granja',25),
	('La Florida',25),
	('La Pintana',25),
	('La Reina',25),
	('Las Condes',25),
	('Lo Barnechea',25),
	('Lo Espejo',25),
	('Lo Prado',25),
	('Macul',25),
	('Maipú',25),
	('Ñuñoa',25),
	('Pedro Aguirre Cerda',25),
	('Peñalolén',25),
	('Providencia',25),
	('Pudahuel',25),
	('Quilicura',25),
	('Quinta Normal',25),
	('Recoleta',25),
	('Renca',25),
	('San Miguel',25),
	('San Joaquín',25),
	('San Ramón',25),
	('Santiago',25),
	('Vitacura',25),
	('El Monte',26),
	('Isla de Maipo',26),
	('Padre Hurtado',26),
	('Peñaflor',26),
	('Talagante',26),
	('Codegua',27),
	('Coínco',27),
	('Coltauco',27),
	('Doñihue',27),
	('Graneros',27),
	('Las Cabras',27),
	('Machalí',27),
	('Malloa',27),
	('Mostazal',27),
	('Olivar',27),
	('Peumo',27),
	('Pichidegua',27),
	('Quinta de Tilcoco',27),
	('Rancagua',27),
	('Rengo',27),
	('Requínoa',27),
	('San Vicente de Tagua Tagua',27),
	('La Estrella',28),
	('Litueche',28),
	('Marchihue',28),
	('Navidad',28),
	('Peredones',28),
	('Pichilemu',28),
	('Chépica',29),
	('Chimbarongo',29),
	('Lolol',29),
	('Nancagua',29),
	('Palmilla',29),
	('Peralillo',29),
	('Placilla',29),
	('Pumanque',29),
	('San Fernando',29),
	('Santa Cruz',29),
	('Cauquenes',30),
	('Chanco',30),
	('Pelluhue',30),
	('Curicó',31),
	('Hualañé',31),
	('Licantén',31),
	('Molina',31),
	('Rauco',31),
	('Romeral',31),
	('Sagrada Familia',31),
	('Teno',31),
	('Vichuquén',31),
	('Colbún',32),
	('Linares',32),
	('Longaví',32),
	('Parral',32),
	('Retiro',32),
	('San Javier',32),
	('Villa Alegre',32),
	('Yerbas Buenas',32),
	('Constitución',33),
	('Curepto',33),
	('Empedrado',33),
	('Maule',33),
	('Pelarco',33),
	('Pencahue',33),
	('Río Claro',33),
	('San Clemente',33),
	('San Rafael',33),
	('Talca',33),
	('Arauco',34),
	('Cañete',34),
	('Contulmo',34),
	('Curanilahue',34),
	('Lebu',34),
	('Los Álamos',34),
	('Tirúa',34),
	('Alto Biobío',35),
	('Antuco',35),
	('Cabrero',35),
	('Laja',35),
	('Los Ángeles',35),
	('Mulchén',35),
	('Nacimiento',35),
	('Negrete',35),
	('Quilaco',35),
	('Quilleco',35),
	('San Rosendo',35),
	('Santa Bárbara',35),
	('Tucapel',35),
	('Yumbel',35),
	('Chiguayante',36),
	('Concepción',36),
	('Coronel',36),
	('Florida',36),
	('Hualpén',36),
	('Hualqui',36),
	('Lota',36),
	('Penco',36),
	('San Pedro de La Paz',36),
	('Santa Juana',36),
	('Talcahuano',36),
	('Tomé',36),
	('Bulnes',37),
	('Chillán',37),
	('Chillán Viejo',37),
	('Cobquecura',37),
	('Coelemu',37),
	('Coihueco',37),
	('El Carmen',37),
	('Ninhue',37),
	('Ñiquen',37),
	('Pemuco',37),
	('Pinto',37),
	('Portezuelo',37),
	('Quillón',37),
	('Quirihue',37),
	('Ránquil',37),
	('San Carlos',37),
	('San Fabián',37),
	('San Ignacio',37),
	('San Nicolás',37),
	('Treguaco',37),
	('Yungay',37),
	('Carahue',38),
	('Cholchol',38),
	('Cunco',38),
	('Curarrehue',38),
	('Freire',38),
	('Galvarino',38),
	('Gorbea',38),
	('Lautaro',38),
	('Loncoche',38),
	('Melipeuco',38),
	('Nueva Imperial',38),
	('Padre Las Casas',38),
	('Perquenco',38),
	('Pitrufquén',38),
	('Pucón',38),
	('Saavedra',38),
	('Temuco',38),
	('Teodoro Schmidt',38),
	('Toltén',38),
	('Vilcún',38),
	('Villarrica',38),
	('Angol',39),
	('Collipulli',39),
	('Curacautín',39),
	('Ercilla',39),
	('Lonquimay',39),
	('Los Sauces',39),
	('Lumaco',39),
	('Purén',39),
	('Renaico',39),
	('Traiguén',39),
	('Victoria',39),
	('Corral',40),
	('Lanco',40),
	('Los Lagos',40),
	('Máfil',40),
	('Mariquina',40),
	('Paillaco',40),
	('Panguipulli',40),
	('Valdivia',40),
	('Futrono',41),
	('La Unión',41),
	('Lago Ranco',41),
	('Río Bueno',41),
	('Ancud',42),
	('Castro',42),
	('Chonchi',42),
	('Curaco de Vélez',42),
	('Dalcahue',42),
	('Puqueldón',42),
	('Queilén',42),
	('Quemchi',42),
	('Quellón',42),
	('Quinchao',42),
	('Calbuco',43),
	('Cochamó',43),
	('Fresia',43),
	('Frutillar',43),
	('Llanquihue',43),
	('Los Muermos',43),
	('Maullín',43),
	('Puerto Montt',43),
	('Puerto Varas',43),
	('Osorno',44),
	('Puero Octay',44),
	('Purranque',44),
	('Puyehue',44),
	('Río Negro',44),
	('San Juan de la Costa',44),
	('San Pablo',44),
	('Chaitén',45),
	('Futaleufú',45),
	('Hualaihué',45),
	('Palena',45),
	('Aisén',46),
	('Cisnes',46),
	('Guaitecas',46),
	('Cochrane',47),
	('O\'higgins',47),
	('Tortel',47),
	('Coihaique',48),
	('Lago Verde',48),
	('Chile Chico',49),
	('Río Ibáñez',49),
	('Antártica',50),
	('Cabo de Hornos',50),
	('Laguna Blanca',51),
	('Punta Arenas',51),
	('Río Verde',51),
	('San Gregorio',51),
	('Porvenir',52),
	('Primavera',52),
	('Timaukel',52),
	('Natales',53),
	('Torres del Paine',53);