variables:
  SERVICE_NAME: "nextdealapi"

stages:
  - build
  - deploy-dev
  - deploy-staging
  - deploy-production

image: google/cloud-sdk:alpine

build:
    environment: staging
    stage: build
    only:
      - main
    before_script:
      - gcloud config set project ${GCP_PROJECT_ID}
      - gcloud auth activate-service-account --key-file ${GCP_SERVICE_ACCOUNT_DEPLOY}
    script:
      - gcloud builds submit --tag gcr.io/${GCP_PROJECT_ID_IMAGES}/${SERVICE_NAME}

deploy-dev:
  environment: dev
  stage: deploy-dev
  only:
    - main
  before_script:
      - gcloud config set project ${GCP_PROJECT_ID}
      - gcloud auth activate-service-account --key-file ${GCP_SERVICE_ACCOUNT_DEPLOY}
  script:
    - gcloud run deploy ${SERVICE_NAME}-dev --image gcr.io/${GCP_PROJECT_ID_IMAGES}/${SERVICE_NAME} --service-account=${GCP_SERVICE_ACCOUNT_API} --region=us-central1 --platform managed --allow-unauthenticated --set-env-vars="JWT_SECRET_KEY=${JWT_SECRET_KEY},JWT_SECRET_KEY_EXPIRE=1d,MYSQL_CONNECTION=${MYSQL_CONNECTION},NEXT_DEAL_SERVICE_URL=${NEXT_DEAL_SERVICE_URL},API_KEY=${API_KEY}" --vpc-connector=${VPC_CONNECTOR} --min-instances=${MIN_INSTANCES} --max-instances=${MAX_INSTANCES} --timeout=50 --ingress=internal-and-cloud-load-balancing

deploy-staging:
  environment: staging
  stage: deploy-staging
  only:
    - main
  before_script:
    - gcloud config set project ${GCP_PROJECT_ID}
    - gcloud auth activate-service-account --key-file ${GCP_SERVICE_ACCOUNT_DEPLOY}
  before_script:
      - gcloud config set project ${GCP_PROJECT_ID}
      - gcloud auth activate-service-account --key-file ${GCP_SERVICE_ACCOUNT_DEPLOY}
  script:
    - gcloud run deploy ${SERVICE_NAME}-staging --image gcr.io/${GCP_PROJECT_ID_IMAGES}/${SERVICE_NAME} --service-account=${GCP_SERVICE_ACCOUNT_API} --region=us-central1 --platform managed --allow-unauthenticated --set-env-vars="JWT_SECRET_KEY=${JWT_SECRET_KEY},JWT_SECRET_KEY_EXPIRE=1d,MYSQL_CONNECTION=${MYSQL_CONNECTION},NEXT_DEAL_SERVICE_URL=${NEXT_DEAL_SERVICE_URL},API_KEY=${API_KEY}" --vpc-connector=${VPC_CONNECTOR} --min-instances=${MIN_INSTANCES} --max-instances=${MAX_INSTANCES} --timeout=50 --ingress=internal-and-cloud-load-balancing
  when: manual

deploy-production:
  environment: production
  stage: deploy-production
  only:
    - main
  before_script:
      - gcloud config set project ${GCP_PROJECT_ID}
      - gcloud auth activate-service-account --key-file ${GCP_SERVICE_ACCOUNT_DEPLOY}
  script:
    - gcloud run deploy ${SERVICE_NAME}-production --image gcr.io/${GCP_PROJECT_ID_IMAGES}/${SERVICE_NAME} --service-account=${GCP_SERVICE_ACCOUNT_API} --region=us-central1 --platform managed --allow-unauthenticated --set-env-vars="JWT_SECRET_KEY=${JWT_SECRET_KEY},JWT_SECRET_KEY_EXPIRE=1d,MYSQL_CONNECTION=${MYSQL_CONNECTION},NEXT_DEAL_SERVICE_URL=${NEXT_DEAL_SERVICE_URL},API_KEY=${API_KEY}" --vpc-connector=${VPC_CONNECTOR} --min-instances=${MIN_INSTANCES} --max-instances=${MAX_INSTANCES} --timeout=50 --ingress=internal-and-cloud-load-balancing
  when: manual