apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: nextdealapi
  namespace: '996123772362'
  selfLink: /apis/serving.knative.dev/v1/namespaces/996123772362/services/nextdealapi
  uid: dd84b23f-938c-4a4e-9869-a70246b6e975
  resourceVersion: AAXMw//Su4c
  generation: 4
  creationTimestamp: '2021-09-24T20:09:07.658679Z'
  labels:
    cloud.googleapis.com/location: us-central1
  annotations:
    run.googleapis.com/client-name: gcloud
    serving.knative.dev/creator: kahtechnologies21@gmail.com
    serving.knative.dev/lastModifier: kahtechnologies21@gmail.com
    client.knative.dev/user-image: gcr.io/next-deal-326621/nextdealapi
    run.googleapis.com/client-version: 358.0.0
    run.googleapis.com/ingress: all
    run.googleapis.com/ingress-status: all
spec:
  template:
    metadata:
      name: nextdealapi-00004-keb
      annotations:
        run.googleapis.com/client-name: gcloud
        client.knative.dev/user-image: gcr.io/next-deal-326621/nextdealapi
        run.googleapis.com/client-version: 358.0.0
        autoscaling.knative.dev/maxScale: '100'
    spec:
      containerConcurrency: 80
      timeoutSeconds: 300
      containers:
      - image: gcr.io/next-deal-326621/nextdealapi
        ports:
        - name: http1
          containerPort: 3000
        resources:
          limits:
            cpu: 1000m
            memory: 512Mi
  traffic:
  - percent: 100
    latestRevision: true
status:
  observedGeneration: 4
  conditions:
  - type: Ready
    status: 'True'
    lastTransitionTime: '2021-09-24T20:57:46.242951Z'
  - type: ConfigurationsReady
    status: 'True'
    lastTransitionTime: '2021-09-24T20:57:40.084833Z'
  - type: RoutesReady
    status: 'True'
    lastTransitionTime: '2021-09-24T20:57:46.242951Z'
  latestReadyRevisionName: nextdealapi-00004-keb
  latestCreatedRevisionName: nextdealapi-00004-keb
  traffic:
  - revisionName: nextdealapi-00004-keb
    percent: 100
    latestRevision: true
  url: https://nextdealapi-al2of5j4vq-uc.a.run.app
  address:
    url: https://nextdealapi-al2of5j4vq-uc.a.run.app
